//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_MyModelFirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5032_MyModelFirstContainer : DbContext
    {
        public FIT5032_MyModelFirstContainer()
            : base("name=FIT5032_MyModelFirstContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<Courses> CoursesSet { get; set; }
        public virtual DbSet<Tutors> TutorsSet { get; set; }
        public virtual DbSet<Students> StudentsSet { get; set; }
        public virtual DbSet<Services> ServicesSet { get; set; }
        public virtual DbSet<Posts> PostsSet { get; set; }
        public virtual DbSet<Classes> ClassesSet { get; set; }
        public virtual DbSet<Registrations> RegistrationsSet { get; set; }
    }
}
